spring:
  application:
    name: system-service
  profiles:
    active: dev

# localhost:8001/actuator/info
info:
  module.name: "Spring Cloud 通用权限管理"
  module.description: "RBAC 权限管理系统模块"
  module.serviceName: ${spring.application.name}
  module.port: ${server.port}
  module.author: "Alex_McAvoy"
  build.artifactId: @project.artifactId@
  build.version: @project.version@